### PR TITLE
README example code corrected

### PR DESCRIPTION
**Pull request by kryptonite0**

### CODE REVIEW

**Comment by avati** [comment]
Have you tried with the git HEAD? the example code looks correct and seems to work fine (on git HEAD)

**Comment by kryptonite0** [comment]
Hello, not sure I understand what you mean. I installed the repo using pip
`pip3 install git+https://github.com/stanfordmlgroup/ngboost`
and the class is called `NGBoost`, not `NGBRegressor`, contrary to the example code that I see in the README on master. Am I missing something?

**Comment by avati** [comment]
Have you tried installing the latest version using ``pip install --upgrade git+https://github.com/stanfordmlgroup/ngboost.git``? I don't get that import error like how you get.

**Comment by kryptonite0** [comment]
`--upgrade` does the job, thanks!

**Pull request merged**
