### PR TITLE
Dataframe compatibility for inputs for fit and predict functions

### PR DESCRIPTION
**Pull request by saianil58**
This is for changes discussed in https://github.com/stanfordmlgroup/ngboost/pull/128

Changes Implemented:

used sklearn functions to validate user inputs for support of pandas dataframe , list, or arrays.

There are also validations for strings or null values which are prohibited

### CODE REVIEW

**Comment by saianil58** [comment]
Test cases and results after fix are here 

https://nbviewer.jupyter.org/github/saianil58/ngboost/blob/master/examples/NGBoost%20Testing%20for%20pr%23129.ipynb

**Comment by saianil58** [comment]
hi alejandroschuler,

Please review the changes and test cases, let me know if you feel anything needs to be edited.

Thanks
Sai

**Comment by alejandroschuler** [comment]
Awesome, I think this looks good. One last thing- would you mind checking how this interacts with survival outcomes? See the [survival regression](https://stanfordmlgroup.github.io/ngboost/1-useage.html#Regression-Distributions) section here.

**Comment by saianil58** [comment]
So, I have checked and it wont work direcly with existing fix, so i updated api.py and helpers.py and now we are good.

Fyi, there seems to be a mistake on the example and I have corrected it and mentioned in the testcase notebook.

Update one is here: https://github.com/saianil58/ngboost/blob/master/examples/NGBoost%20Testing%20for%20pr%23129.ipynb

Let me know your thoughts on this.

Thanks

**Comment by tonyduan** [comment]
> Fyi, there seems to be a mistake on the example and I have corrected it and mentioned in the test case notebook.

Could you elaborate on this? Which file does the mistake lie in?

**Comment by saianil58** [comment]
This piece of code when ran separately gives an error "NameError: name 'Y_train' is not defined"
image

the corrected part is on cell 6 in the notebook https://github.com/saianil58/ngboost/blob/master/examples/NGBoost%20Testing%20for%20pr%23129.ipynb

**Comment by tonyduan** [comment]
@saianil58 Huh, your version of the code doesn't match what I'm seeing on the master branch of `examples/survival.py`. The version below runs without issue for me.

Screen Shot 2020-06-03 at 11 13 28 AM

**Comment by saianil58** [comment]
> One last thing- would you mind checking how this interacts with survival outcomes? See the survival regression section here.

I was looking on the page given from the above comment and I assume that the page example is not yet updated.

image


Regarding the fix for dataframe compatibility do you have any further concerns...

**Comment by saianil58** [comment]
@alejandroschuler and @tonyduan,

Are you okay with this change being merged with master code. So that we can work on closing this pr.

**Comment by tonyduan** [comment]
Thanks for pointing out the mistake in the online documentation; I've pushed a fix.

I'm not as familiar with the PR so I'll let @alejandroschuler review it for merge.

**Comment by alejandroschuler** [comment]
@saianil58 looks great. Thanks so much for working on this!

**Pull request merged**
