### PR TITLE
Survival pickle

### PR DESCRIPTION
**Pull request by MikeOMa**
- Made NGBSurvival pickleable. This will not work if the base Dist is not pickleable itself. I assume this would be quite rare though?
- Added pickle tests from the test-pickle branch. I hope it gives credit to Ryan as it is all their code! I think I used checkout to copy it directly from the branch.
- Testing was taking quite a while so I turned down the number of iterations in the MVN test and the pickle tests
- Fixed a small typo in the __getstate__ comments.

Should close 
https://github.com/stanfordmlgroup/ngboost/issues/238
https://github.com/stanfordmlgroup/ngboost/issues/228

Can change any of it/try to improve it if anyone has any ideas!

### CODE REVIEW

**Comment by MikeOMa** [comment]
Any ideas about why make lint on my local pc gives me different results to github actions?
I'll sort the failed checks out tomorrow

**Comment by MikeOMa** [comment]
Realised putting the class factory SurvivalDistnClass in api is probably a bad idea as people may attempt to use it. Moving it to distns

**Review by alejandroschuler — APPROVED** [review]
Looks good, thanks for the fix!

**Comment by alejandroschuler** [comment]
> Realised putting the class factory SurvivalDistnClass in api is probably a bad idea as people may attempt to use it. Should I move it to distns? Also there was a bug in test pickling introduced by me, fixing it in the next commit

You can put it in `distns/utils.py` or something like that

**Comment by ryan-wolbeck** [comment]
> Realised putting the class factory SurvivalDistnClass in api is probably a bad idea as people may attempt to use it. Should I move it to distns? Also there was a bug in test pickling introduced by me, fixing it in the next commit

Are you using ```make lint```? see > https://github.com/stanfordmlgroup/ngboost/pull/204

**Comment by ryan-wolbeck** [comment]
> Any ideas about why make lint on my local pc gives me different results to github actions?
> I'll sort the failed checks out tomorrow
Are you using ```make lint```?
See below
https://github.com/stanfordmlgroup/ngboost/pull/204

**Comment by MikeOMa** [comment]
> > Any ideas about why make lint on my local pc gives me different results to github actions?
> > I'll sort the failed checks out tomorrow
> 
> Are you using `make lint`?
> See below
> #204

Yeah from scratch within the ngboost directory if I run:

```
conda create -n lint_ex_env python=3.8.8
conda activate lint_ex_env
make install
make lint 
```


The last PR passed the above on my local pc. I did not get any of the following.
```
 tests/test_pickling.py:38:4: R0914: Too many local variables (22/15) (too-many-locals)
tests/test_pickling.py:38:4: R0201: Method could be a function (no-self-use)
tests/test_pickling.py:63:4: R0201: Method could be a function (no-self-use)
```

I imagine it is some setting I have set up on my pc. I have disabled some of these checks within pycharm in the past for other projects which might have messed up something.

**Comment by MikeOMa** [comment]
I may have caused some problems, I fixed a typo in the NGBSurvival class which was also fixed by https://github.com/stanfordmlgroup/ngboost/pull/245 

I am pretty the fixes are exactly the same and mine are a subset of #245's fixes.  

If this causes any conflicts/issues I can try to fix them but I'm not sure what the best way is!

**Comment by ryan-wolbeck** [comment]
> I may have caused some problems, I fixed a typo in the NGBSurvival class which was also fixed by #245
> 
> I am pretty the fixes are exactly the same and mine are a subset of #245's fixes.
> 
> If this causes any conflicts/issues I can try to fix them but I'm not sure what the best way is!

I'm not seeing any conflicts so I think we should be good

**Comment by ryan-wolbeck** [comment]
> > > Any ideas about why make lint on my local pc gives me different results to github actions?
> > > I'll sort the failed checks out tomorrow
> > 
> > 
> > Are you using `make lint`?
> > See below
> > #204
> 
> Edit: It is 100% a local problem to me. I ran the above on a virtual machine and it had the same as git.
> Edit2: Deleted ~/.pylintrc and ~/.pylint.d/ and it works as expected now
> Sorry about the confusion

Awesome! I'd recommend running everything in a virtualenv

**Review by ryan-wolbeck — APPROVED** [review]

**Comment by ryan-wolbeck** [comment]
@MikeOMa thanks for doing this! I'm bumping the version then will merge after the tests pass

**Pull request merged**
