### PR TITLE
Add feature importance function on NGBoost

### PR DESCRIPTION
**Pull request by matsuken92**
Adding feature_importance() method for NGBoost class to check feature importance as sum of the each decision tree.

Usage example:
```
data = load_boston()
X, y = data.data, data.target
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2)
ngb = NGBoost(Base=default_tree_learner, Dist=Normal, #Normal, LogNormal
              Score=MLE(), natural_gradient=True, verbose=True,)
ngb.fit(X_train, y_train, X_val=X_valid, Y_val=y_valid)
feature_importance = ngb.feature_importance()
feature_importance_df = pd.DataFrame(feature_importance, index=data.feature_names)
```

https://nbviewer.jupyter.org/github/matsuken92/ngboost/blob/notebooks/examples/notebooks/feature_importance_demo.ipynb

or 

https://github.com/matsuken92/ngboost/blob/notebooks/examples/notebooks/feature_importance_demo.ipynb

### CODE REVIEW

**Comment by avati** [comment]
Hi @matsuken92 thank you for the links! For some reason I am not able to see the notebook contents. Could you make a pull request (preferably with similar API as sklearn)?

**Comment by matsuken92** [comment]
Currently, there are some defect on nbviewer and github, so I can not share the notebook, so I put my screen  shot of the notebook the following. That's a usage of the feature_importance() function.

> preferably with similar API as sklearn

`feature_importance()` function is similar API of LightGBM. However if you want to change, I wiil change accordingly!
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Booster.html#lightgbm.Booster.feature_importance


#### Screen shot of the notebook
screen shot 2019-10-25 2 02 46

**Comment by matsuken92** [comment]
> Could you make a pull request

Sorry, I don't fully understand your request. This is a pull request. If you provide more information, I will do it!

**Comment by avati** [comment]
Ah I see the snapshot now. So it appears that we get a different set of "important features" per parameter? I haven't thought about this much, but what might be the desired behavior? As a user, one might only care about the overall importances of features for the final performance, no matter for which parameter the tree was used in.

Thoughts?

**Comment by matsuken92** [comment]
@avati Thank you for your comment!
Yes, the 2 columns mean for 2 parameters. I think it is better to remain the 2 columns. The reasons of my thought are following

1) The 2 feature importance values are different meaning and different unit of the gain, so if sum up these value, the value can not interpret. 

2) The case of `Normal` dist, the first column is shown the importance of mean, and 2nd column is shown importance of variance. In this example above, most important feat for mean is LSTAT, and most important feat for variance is RM. I think it is useful information.

P.S. I could share the notebook via Kaggle notebook. So please see as reference.
https://www.kaggle.com/kenmatsu4/ngboost-feature-importance-demo

**Comment by avati** [comment]
Hi @matsuken92,

Your reasoning makes sense. Do you know how the importances are reported (say by LightGBM or other sklearn methods) for multi-class classification? Do they report per-class important features, or just overall? In NGBoost, multi-class classification and mean-var of regression are treated equally as "multiple parameters", and so the decision of how we choose to report features will apply to all methods uniformly.

On a separate note, we want to make feature importance be optional / dependent on the choice of base learner. One of my plan for the near term is to add support for MondrianTree as base learner (https://scikit-garden.github.io/examples/MondrianTreeRegressor/), and I am not sure how common it will be for future base learners to all support feature importance.

**Comment by matsuken92** [comment]
> Do you know how the importances are reported (say by LightGBM or other sklearn methods) for multi-class classification?

In that case, just 1 importance feature for the overall at LightGBM. 
Hmm...
My suggestion for the multi-class classification is that summing up for all mean importance and variance importance. Then we can keep a consistency with above behavior. 

> we want to make feature importance be optional / dependent on the choice of base learner. 

For dependency, it may be better the default_tree_learner to change class and the class have feature_importance method. In that case we can separate the implementation of feature_importance from ngboost.py.

>  I am not sure how common it will be for future base learners to all support feature importance.

Oh, you are right. The feature importance is used mainly tree based algorithm. And MondrianTreeRegressor has also feature_importance_ attribute  ([API Doc](https://scikit-garden.github.io/api/#skgardenmondrianmondriantreeregressor) ) However if default_linear_learner(Ridge) is used, we can not calculate the feature importance... 
LightGBM has only decision tree based learner, so it is no problem...

We need to discuss further.

**Comment by matsuken92** [comment]
And this is just my out of interest, what is the reason you need to adopt MondrianTree for the learner which is the first I've heard. I would appreciate it if you could provide the good feature comparing with sklearn's Decision Tree.
Thank you!

**Comment by avati** [comment]
In theory Mondrian Trees should give better uncertainty estimates for examples that are "far away" from the training set. The link I shared above has a good introductory article for how it works.

**Comment by alejandroschuler** [comment]
hey @matsuken92, could you have a look at this pull request and let me know if you think it covers what you want: https://github.com/stanfordmlgroup/ngboost/pull/27? I think it implements what you need but also covers some other ground so I'm inclined to close this pull request and accept that one instead. Please feel free to make comments to that request and join the conversation there!

**Comment by alejandroschuler** [comment]
Closing in light of https://github.com/stanfordmlgroup/ngboost/pull/27

**Comment by alejandroschuler** [comment]
Closing in light of https://github.com/stanfordmlgroup/ngboost/pull/27

**Pull request closed without merging**
