### PR TITLE
Add scikit-learn API

### PR DESCRIPTION
**Pull request by yutayamazaki**
- add scikit-learn API models; Regressor and (Binary)Classifier
- also add their examples to use GridSearchCV reported in [this isssue](https://github.com/stanfordmlgroup/ngboost/issues/7).

### CODE REVIEW

**Comment by avati** [comment]
This is great, thank you! A couple of comments:

- rename NGBoostClassifier to NGBClassifier (and similarly NGBRegressor)

- we want users to be able to 'from ngboost import NGBClassifier', so register in init.

- also update README.md to reflect the new API

**Comment by yutayamazaki** [comment]
Thank you for your feedback.  
I dealt with these problems. Please check them.

**Comment by avati** [comment]
Two final comments:

- The branch needs to be rebased against the latest HEAD of master (there are merge conflicts right now)

- For README.md, let's just make edits to the current example and make it use the new NGBRegressor class (and remove the Dist and Score parameters). We don't need the gridsearchcv etc in that example.

With these edits we should be good for merge!

**Comment by yutayamazaki** [comment]
I updated the example in README.md.   And now, we have no merge conflict. Is it enough to merge?

**Comment by avati** [comment]
I could not rebase it due to conflicts, so squashed and merged as single commit.

Thank you for the great contribution @yutayamazaki !

**Pull request merged**
