### PR TITLE
added Gamma distribution

### PR DESCRIPTION
**Pull request by eco3**
Added Gamma distribution with the PDF 

$$
f(y;\alpha, \beta) = \frac{1}{\Gamma(\alpha)} \frac{(\beta y)^\alpha}{y} \mathrm{e}^{-\beta y}.
$$

I used [SciPys gamma distribution](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gamma.html#scipy.stats.gamma) for this implementation.
Both parameters $\eta = (\alpha, \beta) > 0$. Therefore I reparametrized them to $\theta = (\log \alpha, \log \beta)$.

For the LogScore I calculated the derivatives with respect to [log a](https://www.wolframalpha.com/input?i2d=true&i=D%5B-log%5C%2840%29Divide%5BPower%5B%5C%2840%29Power%5Be%2Cb%5D+y%5C%2841%29%2CPower%5Be%2Ca%5D%5D%2C%5CGamma%5C%2840%29Power%5Be%2Ca%5D%5C%2841%29+y%5DPower%5Be%2C-yPower%5Be%2Cb%5D%5D%5C%2841%29%2Ca%5D) and [log b](https://www.wolframalpha.com/input?i2d=true&i=D%5B-log%5C%2840%29Divide%5BPower%5B%5C%2840%29Power%5Be%2Cb%5D+y%5C%2841%29%2CPower%5Be%2Ca%5D%5D%2C%5CGamma%5C%2840%29Power%5Be%2Ca%5D%5C%2841%29+y%5DPower%5Be%2C-yPower%5Be%2Cb%5D%5D%5C%2841%29%2Cb%5D).

$$
\begin{align*}
   \frac{\partial f}{\partial \alpha} &= \alpha(\psi^{(0)}(\alpha) - \log(\beta\ y)) \\
   \frac{\partial f}{\partial \beta}   &= \beta y - \alpha
\end{align*}
$$

With $\psi^{(m)}(z)$ being the [polygamma function of order m](https://en.wikipedia.org/wiki/Polygamma_function). SciPy offers [this function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.polygamma.html).
$\psi^{(0)}(z)$ is the [digamma function](https://en.wikipedia.org/wiki/Digamma_function), which is also [supported by SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.digamma.html).

The [Fisher information matrix of the gamma distribution](https://www2.stat.duke.edu/courses/Spring16/sta532/lec/fish.pdf) is

$$
  I_{\eta}(\eta) = 
  \begin{pmatrix}
    \psi^{(1)}(\alpha) & -\beta^{-1}\\
    -\beta^{-1} & \alpha \beta^{-2}
  \end{pmatrix}.
$$

The reparameterisation procedure yields the following matrix:

$$
\begin{align*}
   I_{\theta}(\theta) &= J^{-1}\ I_{\eta}(\eta)\ J^{-1} \\
   I_{\theta}(\theta) &= 
	\begin{pmatrix}
		\alpha & 0\\
		0 & \beta
	\end{pmatrix}
	\begin{pmatrix}
		\psi^{(1)}(\alpha) & -\beta^{-1}\\
		-\beta^{-1} & \alpha \beta^{-2}
	\end{pmatrix}
	\begin{pmatrix}
		\alpha & 0\\
		0 & \beta
	\end{pmatrix} \\
   I_{\theta}(\theta) &= 
	\begin{pmatrix}
		\alpha^2\ \psi^{(1)}(\alpha) & -\alpha\\
		-\alpha & \alpha
	\end{pmatrix}
\end{align*}
$$

I'm no expert in maths, somebody should doublecheck my calculations.
I added the distribution to the tests, not sure if I missed something. The pytests passed on my machine.

### CODE REVIEW

**Comment by ryan-wolbeck** [comment]
@alejandroschuler can you review the math here and I'll focus on implementation?

**Comment by alejandroschuler** [comment]
@eco3 thanks for the contribution! Could you use wolframalpha.com to verify the derivations please?

**Comment by eco3** [comment]
> @eco3 thanks for the contribution! Could you use wolframalpha.com to verify the derivations please?

I've already posted them in the original post, here they are: [df/da](https://www.wolframalpha.com/input?i2d=true&i=D%5B-log%5C%2840%29Divide%5BPower%5B%5C%2840%29Power%5Be%2Cb%5D+y%5C%2841%29%2CPower%5Be%2Ca%5D%5D%2C%5CGamma%5C%2840%29Power%5Be%2Ca%5D%5C%2841%29+y%5DPower%5Be%2C-yPower%5Be%2Cb%5D%5D%5C%2841%29%2Ca%5D) and [df/db](https://www.wolframalpha.com/input?i2d=true&i=D%5B-log%5C%2840%29Divide%5BPower%5B%5C%2840%29Power%5Be%2Cb%5D+y%5C%2841%29%2CPower%5Be%2Ca%5D%5D%2C%5CGamma%5C%2840%29Power%5Be%2Ca%5D%5C%2841%29+y%5DPower%5Be%2C-yPower%5Be%2Cb%5D%5D%5C%2841%29%2Cb%5D).
I'll then substituted $e^a$ and $e^b$ with $e^{\log a}$ and $e^{\log b}$. This yields: [df/da substituted](https://www.wolframalpha.com/input?i2d=true&i=Power%5Be%2Clog%5C%2840%29a%5C%2841%29%5D+%5C%2840%29-log%5C%2840%29Power%5Be%2Clog%5C%2840%29b%5C%2841%29%5D+y%5C%2841%29+%2B+polygamma%5C%2840%290%5C%2844%29+Power%5Be%2Clog%5C%2840%29a%5C%2841%29%5D%5C%2841%29%5C%2841%29) and [df/db substituted](https://www.wolframalpha.com/input?i2d=true&i=-Power%5Be%2Clog%5C%2840%29a%5C%2841%29%5D+%2B+Power%5Be%2Clog%5C%2840%29b%5C%2841%29%5D+y).

**Comment by alejandroschuler** [comment]
@eco3 oh, so sorry about that, I totally missed the links :)

**Review by alejandroschuler — APPROVED** [review]
math looks good!

**Comment by ryan-wolbeck** [comment]
@eco3 can you please run black code formatting on the PR https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
That should take care of the failed builds

**Comment by eco3** [comment]
> @eco3 can you please run black code formatting on the PR https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html That should take care of the failed builds

After running black for formatting, there are still some failed checks, see [here](https://github.com/stanfordmlgroup/ngboost/actions/runs/3080952949/jobs/4978923199#step:5:35).

Is this related to [this issue](https://github.com/psf/black/issues/2976)?

**Comment by ryan-wolbeck** [comment]
@eco3 that looks like a likely culprit to me, I'll take a deeper look at this during this week and get back to you (thinking likely just bump the version of black to latest)

**Review by ryan-wolbeck — APPROVED** [review]

**Pull request merged**
