### PR TITLE
Add CodeQL security scanning

### PR DESCRIPTION
**Pull request by daikikatsuragawa**
I propose to introduce CodeQL (code scanning)  to this project.
This is to prevent security problems hidden in the code.

https://securitylab.github.com/tools/codeql

### CODE REVIEW

**Comment by ryan-wolbeck** [comment]
@daikikatsuragawa Can you give us some context here?

**Comment by daikikatsuragawa** [comment]
I'm sorry that the explanation is missing.
The description has been updated.

https://github.com/stanfordmlgroup/ngboost/pull/210#issue-520701277

**Comment by ryan-wolbeck** [comment]
@daikikatsuragawa I'll take a look, in the mean time the build in 3.6 failed if you want to triage

**Comment by ryan-wolbeck** [comment]
bump @daikikatsuragawa, can you triage to fix the build issues?

**Comment by ryan-wolbeck** [comment]
Closing until an update occurs, feel free to re-open when fixed

**Pull request closed without merging**
