### PR TITLE
Updating black formatter to latest

### PR DESCRIPTION
**Pull request by robertsont**

### CODE REVIEW

**Comment by ryan-wolbeck** [comment]
Thank you for the PR, I think we will just need to run black locally and push and this should pass

**Comment by ryan-wolbeck** [comment]
It looks like our build on 3.6 is getting stuck resolving dependencies, can you modify the makefile https://github.com/stanfordmlgroup/ngboost/blob/master/Makefile to be 'pip install poetry==1.2.1 && poetry install' and push one more time?

**Comment by robertsont** [comment]
Seems poetry is not supported on versions of python older than 3.7
image

Might be worth considering abandoning 3.6. Also, building for 3.9 and 3.10 is something to think about as well.

**Comment by xmnlab** [comment]
I think that it makes total sense.

**Comment by ryan-wolbeck** [comment]
@robertsont yeah I think moving away from 3.6 makes sense especially because Python itself has dropped support. Can you update this pr to remove 3.6 and include 3.9/3.10? I think we will need to modify line 14 in .github/workflows/pythonpackage.yml and line 16 of pyproject.toml

Tagging @alejandroschuler just so you are aware of this change

**Comment by ryan-wolbeck** [comment]
@robertsont I think we will need to update the version on numpy for 3.10, while you are in there can you also update python to be >= 3.7

**Comment by robertsont** [comment]
Fixing the tests now. Also taking the suggestion from the scikit-learn maintainers to _not_ use the `load_boston()` data set and instead use the `fetch_california_housing()` data set.

**Comment by ryan-wolbeck** [comment]
Yeah versions look good, thanks for updating that test set.

**Comment by ryan-wolbeck** [comment]
@robertsont I think we might have to bump the version of numpy up as well

**Comment by ryan-wolbeck** [comment]
Closed by #301

**Pull request closed without merging**
