### PR TITLE
Add set_params for sklearn compatibility.

### PR DESCRIPTION
**Pull request by jckkvs**
Add set_params, get_params for sklearn compatibility.
This change makes it easier to use with optimization libraries such as optuna or GridSearchCV.
https://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html

Here is the pseudo code.
```
model = NGBoost(Base=default_tree_learner, Dist=Normal, natural_gradient=True, verbose=False)
def objective(trial):
    return something

study = optuna.create_study()
study.optimize(objective, n_trials=10)
model.set_params(study.best_params)
```

### CODE REVIEW

**Review by alejandroschuler — APPROVED** [review]

**Review by ryan-wolbeck — CHANGES_REQUESTED** [review]
Tests are failing on a linting issue, I think because there is an extra line on 402 that needs to be removed. Please run `make lint` to fix those issues automatically then run `make test` to ensure everything else passes then commit and I will review again

**Comment by ryan-wolbeck** [comment]
@jckkvs It's still failing, I tried to push but I'd need permissions on the fork you have. You'll still need to run black for this to pass so, `black ngboost/ngboost.py` should do it.

**Comment by jckkvs** [comment]
@ryan-wolbeck 
I applied black to ngboost.py

**Comment by ryan-wolbeck** [comment]
@jckkvs can you pull the current version of master into this PR? It should fix the f-string issue, @robertsont pushed a fix in that with the version bump https://github.com/stanfordmlgroup/ngboost/pull/286/files. So pulling master should make this PR pass

**Comment by ryan-wolbeck** [comment]
@jckkvs can you make the required updates here? I'll be closing this next week if it doesn't get resolved and pushing fixes on my own.

**Comment by ryan-wolbeck** [comment]
implemented and released in another PR

**Pull request closed without merging**
