### PR TITLE
Add feature importance and SHAP support for tree learners

### PR DESCRIPTION
**Pull request by zhiruiwang**
For default_tree_learners, added sklearn-like feature importance, and also added [SHAP](https://github.com/slundberg/shap) support. For each parameter in the destribution, corresponding APIs will generate one feeature importance and SHAP plot.

Please check out the [notebook](https://github.com/zhiruiwang/ngboost/blob/master/examples/visualizations/Feature%20importance_SHAP%20plot.ipynb) for testing examples.

### CODE REVIEW

**Comment by TSFelg** [comment]
That will be very useful @zhiruiwang, thanks! I'm probably going to test this soon, I'll get back if I have some feedback.

**Comment by abarbosa94** [comment]
Hey guys! I loved NG Boost package and I was also looking for this kind of feature (SHAP implementation)

Are there any plans to merge this one soon?  :)

Thanks!

**Comment by alejandroschuler** [comment]
hey @abarbosa94, none of us have had time to go over this in detail so that's why it's still pending. On the other hand, it doesn't impact any of the core functionality, so I'm inclined to accept it with the caveat that it's not supported or tested by anyone other than @zhiruiwang. Are you (@abarbosa94) interested in reviewing the code to make sure it's a correct extension of SHAP to ngboost and testing it out? If so, I'm happy to accept the pull so you can start using it.

**Comment by abarbosa94** [comment]
I can give it a try :) but I think that it might gonna take a while since I would probably gonna do this in my spare time. I'll try to handle this over the weekend. 

Anyway, thanks for the opportunity :)

**Comment by alejandroschuler** [comment]
This is brilliant, thank you @abarbosa94!

I agree with both of your points. For now I'll just add the feature importance method and I'll modify it so that the names of the parameters are apparent.

@zhiruiwang, could you 1) make a new PR including only the feature importance method (I'll adjust it later myself to include named parameters) and 2) submit the rest of your code to the shap project instead of here? After it's accepted there we can revise your notebook example accordingly so that people know those features are available via the shap package. 

I'm going to close this PR for now, but feel free to continue discussing here. Thanks to all for the valuable input! Look forward to having these features available.

**Comment by zhiruiwang** [comment]
@abarbosa94 @alejandroschuler Thanks for your advice, I will make a new pull request

**Pull request closed without merging**
