### PR TITLE
Add partial fit method to match sklearn API

### PR DESCRIPTION
**Pull request by CompRhys**
Currently calling fit on an already trained model simply appends to the base model list. This results in misleading results in CV. I have moved old fit method to partial fit and then explicitly reset the lists in the fit call.

### CODE REVIEW

**Comment by jack-mcivor** [comment]
@CompRhys think you need to run black - probably just removing [line 259](https://github.com/CompRhys/ngboost/blob/master/ngboost/ngboost.py#L259)

**Comment by CompRhys** [comment]
Also if this `partial_fit` behaviour was always a bug then perhaps it should be completely removed. Here the aim was to ensure that people who may have designed code around this append operation which differs from the sklearn API would be able to continue to use the model as before by slightly refactoring (provided not using the model inside a sklearn `Pipeline`)

**Comment by alejandroschuler** [comment]
> Also if this `partial_fit` behaviour was always a bug then perhaps it should be completely removed. Here the aim was to ensure that people who may have designed code around this append operation which differs from the sklearn API would be able to continue to use the model as before by slightly refactoring (provided not using the model inside a sklearn `Pipeline`)

It wasn't intended to be used this way but I think it's a good idea to officially support it.

**Review by alejandroschuler — APPROVED** [review]

**Comment by CompRhys** [comment]
This is a fairly major bug imo so would be good to merge when possible

**Comment by alejandroschuler** [comment]
@ryan-wolbeck

**Review by ryan-wolbeck — APPROVED** [review]
lgtm, sorry for the delay I'm transitioning computers at the moment. I'll publish out a new version today to tomorrow to pypi

**Pull request merged**
