### PR TITLE
dataframe compatibility

### PR DESCRIPTION
**Pull request by saianil58**
dataframe compatibility for inputs of .fit and .predict functions

This is for issue https://github.com/stanfordmlgroup/ngboost/issues/127

### CODE REVIEW

**Comment by alejandroschuler** [comment]
hey @saianil58 thanks for the contribution! 

It looks like your PR introduces a new copy of `ngboost.py` in the root directory rather than editing the one that's at `ngboost/ngboost.py`. For this to work properly you'll have to edit that file in-place instead of add a new file.

More importantly, however, I'm not sure how useful this functionality is. Obviously it's a convenience, but what's wrong with asking the user to call `.to_numpy()` on their dataframes themselves? Doing it internally obfuscates the fact that all we're doing is calling `.to_numpy()` and that there is no special handling of categorical/time-series columns, etc. See #94 

I'm not strictly opposed to a dataframe interface but if we're going to have one, I want it to be flushed-out with validation of user input of different types and clear documentation.

**Comment by saianil58** [comment]
hi alejandroschuler,

I was trying to integrate NGBoost with something else that I have already built and as all the sklearn models accept the data frames directly it would be easier is what I have thought. 

Yes, handling the categorical features is not an easy option with more than one way to do it and user should have choice with him. 

Yes, it's just a convenience that we are trying to have and at the same time making the inputs similar along with multiple other implementations.

There are other implementations that would accept only numeric data and supports Numpy and DataFrames. I was thinking on those lines.

**Comment by alejandroschuler** [comment]
@saianil58 can we simply copy whatever sklearn does to transform dataframes to numpy arrays?

**Comment by saianil58** [comment]
that is possible and the implementation is here,
https://github.com/scikit-learn/scikit-learn/blob/332aaa112b1ed02bcf0ce38e0901d3ea5eaf6e3a/sklearn/utils/validation.py#L400

but it's part of utils and they are handling validation internally and throwing an error if its not passed

**Comment by alejandroschuler** [comment]
Oh, cool. Can we just import and call that function, then?

**Comment by saianil58** [comment]
I will verify in that direction and will let you know

**Comment by saianil58** [comment]
closing this as creating a new pr

**Pull request closed without merging**
