### PR TITLE
Setup tox to enable testing with multiple python versions locally

### PR DESCRIPTION
**Pull request by zyxue**
for testing against multiple python versions locally

more info about tox is available at https://tox.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by ryan-wolbeck** [comment]
@zyxue can you provide context on the value prop with tox?

**Comment by zyxue** [comment]
otherwise, what's the recommended way to run tests locally for multiple versions of python?

**Comment by zyxue** [comment]
for example, I was trying to make sure
```
try:
    from importlib.metadata import version
except ImportError:
    # before python 3.8
    from importlib_metadata import version
```
works for all python versions locally in https://github.com/stanfordmlgroup/ngboost/pull/229/

**Comment by ryan-wolbeck** [comment]
@zyxue I'm not saying there is a better way I'm asking you to explain the important of using TOX generally so people understand the need for this PR

**Comment by zyxue** [comment]
I see. I've updated the title to make the purpose of using tox more explicit.

**Review by ryan-wolbeck — APPROVED** [review]

**Pull request merged**
